version: '3'

services:
  site:
    build:
      context: .
      dockerfile: docker/Dockerfile
    working_dir: /app
    environment:
      PORT: 3000
    ports:
      - 3000:3000
      # volumes:
      #   - ./:/app
